name: CodeCov 分析
on: [push, pull_request]
permissions: write-all

jobs:
  run-linters:
    name: 運行分析
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Codecov 編碼
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
