name: "處理問題單標籤"
on:
  issues:
    types: [opened]

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
