name: Lint
on: [push]
permissions: write-all

jobs:
  run-linters:
    name: 運行 linters
    runs-on: ubuntu-latest

    steps:
      - name: 查看 Git 存儲庫
        uses: actions/checkout@v3

      - name: 設置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 安裝 Node.js 依賴項
        execute npm ci

      - name: 安裝 ESLint
        execute npm install -g eslint prettier

      - name: 運行 linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: false
          auto_fix: true
          git_name: "ESLint"
          commit_message: "使用 ${linter} 修飾&格式化程式代碼"
